-- "Mostrar Notas" (Gestão → Bloqueios e Liberações) — o aluno só vê a NOTA
-- (e o selo Aprovado/Recuperação) de cada matéria, na aba Perfil, depois
-- que o professor liga isso PRA O BIMESTRE ATUAL especificamente. Evita
-- mostrar nota baixa de um bimestre ainda em andamento, com lançamento
-- incompleto. Rode UMA vez no SQL Editor do Supabase — é seguro rodar de
-- novo (idempotente). É o mesmo trecho que está em
-- sql/supabase-setup-completo.sql, pra quem já tem o banco montado e não
-- quer rodar o script completo de novo.
--
-- default false: todo bimestre nasce bloqueado (ver bimestre_dates), então
-- o professor não precisa lembrar de bloquear de novo quando um bimestre
-- novo começa — só liga quando terminar de lançar as notas daquele
-- bimestre (ver toggleNotasLiberadas em shared/platform-core.js).
alter table public.bimestre_dates add column if not exists notas_liberadas boolean not null default false;
