-- Remove a feature "Ocultar Jogos" (esconder um módulo/jogo específico da
-- lista do aluno enquanto ainda estava em desenvolvimento) — não é mais
-- necessária, a tela de Gestão que a controlava saiu de "Bloqueios e
-- Liberações". Rode UMA vez no SQL Editor do Supabase — é seguro rodar de
-- novo (idempotente). É o mesmo trecho que está em
-- sql/supabase-setup-completo.sql, pra quem já tem o banco montado e não
-- quer rodar o script completo de novo.
--
-- Sem dado de aluno nenhum na tabela (só configuração manual do
-- professor) — seguro derrubar de vez.
drop table if exists public.hidden_modules cascade;
